MODEL:
  arch: interpcnn2  # backbone network architecture

TRAIN:
  exp_name: interpcnn2_train
  num_points: 1024
  pt_norm: False  # input normalization
  batch_size: 1 #32
  test_batch_size: 1 #16
  epochs: 350
  lr: 0.1
  momentum: 0.9
  eval: False
  gpus: [0, 1]